# 베이스 이미지를 설정합니다.
FROM ubuntu:18.04

# 컨테이너 안에서 파일을 생성할 디렉토리를 설정합니다.
WORKDIR /app

# # dummy.txt 파일을 생성하는 명령어를 추가합니다.
# RUN dd if=/dev/zero of=dummy.txt count=1000 bs=1

# # 컨테이너가 시작될 때 실행될 명령어를 설정합니다.
# CMD ["bash"]
